### ISSUE TITLE
Tests time out

### ISSUE THREAD

**Issue by stevenvachon** [bitovi/testee#118]
```js
'use strict'
const testee = require('testee');

const browsers = [
  { os:'Windows', os_version:'7',  browser:'ie', browser_version:'9.0' },
  { os:'Windows', os_version:'8',  browser:'ie', browser_version:'10.0' },
  { os:'Windows', os_version:'10', browser:'ie', browser_version:'11.0' },
  { os:'Windows', os_version:'10', browser:'edge', browser_version:'13.0' },
  { os:'Windows', os_version:'10', browser:'edge', browser_version:'14.0' }
];

const options = {
  reporter: 'spec',
  tunnel: {
    type: 'browserstack',
    key: process.env.BROWSERSTACK_KEY
  },
  launch: {
    type: 'browserstack',
    username: process.env.BROWSERSTACK_USERNAME,
    password: process.env.BROWSERSTACK_KEY,
    version: 4
  }
};

testee.test(['test.html'], browsers, options);
```

```
  1) General error http://localhost:3996/test.html?__token=91pk8j on {"os":"Windows","os_version":"7","browser":"ie","browser_version":"9.0"}:
     Error: Browser timed out within 120 seconds
      at Timeout.testTimedOut [as _onTimeout] (/project/node_modules/testee/lib/runner.js:43:42)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by daffl** [comment]
I got a test to work on Browserstack with version 4 of the API using the following configuration:

```js
{
  "reporter": "Spec",
  "tunnel": {
    "type": "browserstack",
    "key": "<access key>"
  },
  "launch": {
    "type": "browserstack",
    "username": "<username>",
    "password": "<access key>",
    "version": 4
  },
  "browsers": [{
    "os": "OS X",
    "os_version": "Sierra",
    "browser": "firefox",
    "device": null,
    "browser_version": "47.0"
  }]
}
```

Timeout reasons might be due to a limit of concurrent tests or a wrong username/access key.

**Comment by stevenvachon** [comment]
It was due to the path to the file. I had it in a test/ dir off the project root, which messed with the cwd. Thanks!
