### ISSUE TITLE
Provide more information on a timeout error

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/testee#148]
We see build errors pretty often like:

https://travis-ci.org/canjs/canjs/builds/253644821#L3694

```
     Error: Browser timed out within 120 seconds
      at Timeout.testTimedOut [as _onTimeout] (/home/travis/build/[secure]/[secure]/node_modules/testee/lib/runner.js:47:27)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)
```

I'm not sure if this is testee, or our build.  One way to tell is if testee encounters a timeout error, it should scrape the `HTML` content of the page and print it (or even a subset of it) for the user.  And also may forward any caught `window.onerror` messages.

**Comment by andrejewski** [comment]
This would be great. Needs coordination between `testee` and `testee-client` but I think its feasible.

**Comment by andrejewski** [comment]
I am thinking of adding a preflight browser check where Testee starts a browser, points it at a simple HTTP server and once a request is received we shutdown the server and continue the normal test flow. The value here is that we can provide a much better error about a browser launch failure as opposed to someone's own test errors.

This is just one idea.
