### ISSUE TITLE
Unhandled Promise Rejection: No assertion/no test

### ISSUE THREAD

**Issue by mrpaws** [bitovi/testee#178]
I have no tests in the test directory, even when I add some they are not detected.  Error and gruntfile below.  Not sure what it's trying to do.  Happens intermittently seemingly without alteration of operating environment (ie, run it over and over and sometimes it doesn't throw the error).

```
Running "qunit:files" (qunit) task
>> 0 tests completed with 0 failed, 0 skipped, and 0 todo.
>> 0 assertions (in 0ms), passed: 0, failed: 0
(node:7180) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.addScriptToEvaluateOnNewDocument): Target closed.
  at Promise (c:\Repos\phaser-play\node_modules\puppeteer\lib\Connection.js:202:56)
  at new Promise (<anonymous>:null:null)
  at CDPSession.send (c:\Repos\phaser-play\node_modules\puppeteer\lib\Connection.js:201:12)
  at Page.evaluateOnNewDocument (c:\Repos\phaser-play\node_modules\puppeteer\lib\Page.js:774:24)
  at c:\Repos\phaser-play\node_modules\grunt-contrib-qunit\tasks\qunit.js:405:14
  at <anonymous>:null:null
  at process._tickCallback (internal/process/next_tick.js:188:7)

(node:7180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
module.exports = function(grunt) {

  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    concat: {
      options: {
        separator: ';'
      },
      dist: {
        src: ['src/**/*.js'],
        dest: 'dist/<%= pkg.name %>.js'
      }
    },
    uglify: {
      options: {
        banner: '/*! <%= pkg.name %> <%= grunt.template.today("dd-mm-yyyy") %> */\n'
      },
      dist: {
        files: {
          'dist/<%= pkg.name %>.min.js': ['<%= concat.dist.dest %>']
        }
      }
    },
    qunit: {
      files: ['test/**/*.html']
    },
    jshint: {
      files: ['Gruntfile.js', 'src/**/*.js', 'test/**/*.js'],
      options: {
        // options here to override JSHint defaults
        globals: {
          jQuery: true,
          console: true,
          module: true,
          document: true
        }
      }
    },
    watch: {
      files: ['<%= jshint.files %>'],
      tasks: ['jshint', 'qunit']
    }
  });

  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-contrib-qunit');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-connect');

  grunt.registerTask('test', ['jshint', 'qunit']);
  grunt.registerTask('serve', ['connect']);

  grunt.registerTask('default', ['jshint', 'qunit', 'concat', 'uglify']);

};
```

**Comment by mrpaws** [comment]
Ah.  It needed an html file in the directory it seems?  I swear it happens intermittently, but when I added a qunit .html test boilerplate from https://qunitjs.com/cookbook/ to ./test/test_tests/hello.html , I can no longer reproduce.  If it's the lack of existence of an expected file, this could be more clear in the output.
