### ISSUE TITLE
Instructions don't work

### ISSUE THREAD

**Issue by valtido** [bitovi/testee#22]
On Windows - I followed the instructions from https://github.com/bitovi/testee.js/ on getting started section.

I got the following error when I entered the command ... 

```testee tests/qunit.html --browser firefox```
also this but same result
``` testee tests/qunit.html```

```
C:\Users\[username]\AppData\Roaming\npm\node_modules\testee\lib\server\index.js:85
                        throw new Error('Can not do anything for protocol ' + root.protocol);
                              ^
Error: Can not do anything for protocol c:
    at Object.module.exports.createServer (C:\Users\[username]\AppData\Roaming\npm\node_modules\testee\lib\server\index.js:85:10)
    at createServer (C:\Users\[username]\AppData\Roaming\npm\node_modules\testee\lib\testee.js:64:22)
    at Object.test (C:\Users\[username]\AppData\Roaming\npm\node_modules\testee\lib\testee.js:90:15)
    at runTests (C:\Users\[username]\AppData\Roaming\npm\node_modules\testee\bin\testee:10:9)
    at Object.<anonymous> (C:\Users\[username]\AppData\Roaming\npm\node_modules\testee\bin\testee:56:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Here is some system info 

```

>npm version
{ http_parser: '1.0',
  node: '0.10.5',
  v8: '3.14.5.8',
  ares: '1.9.0-DEV',
  uv: '0.10.5',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e',
  npm: '1.2.18' }
```

Running on windows 7 

Ask any questions if you need more information regarding the above ...

**Comment by daffl** [comment]
This has also been fixed for a while in the latest version.
