### ISSUE TITLE
Not able to run tests with PhantomJS

### ISSUE THREAD

**Issue by pavankmv** [bitovi/testee#95]
Command Executed: 
testee src\main\test.html

Output: 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn D:\My_Project\implementation\interface\node_modules\.bin\phantomjs ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by daffl** [comment]
Can you also paste the output with the `DEBUG=testee*` environment variable set?

**Comment by stevenvachon** [comment]
My tests run, but the process takes a long time to exit (~45 seconds).

**Comment by andrejewski** [comment]
@pavankmv Any new developments on your end?
